apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80           # Port exposé pour accès externe
      targetPort: 8088   # Port d'écoute du conteneur
