apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8088
        env:
        - name: DATABASE_DATABASE
          value: "messages"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: myapp-credentials
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-credentials
              key: POSTGRES_PASSWORD
        - name: DATABASE_HOST
          value: "postgres-service.db-namespace.svc.cluster.local"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
